# netlify.toml
[[headers]]
for = "/build_test/Build/*.wasm"
  [headers.values]
  Content-Type = "application/wasm"

[[headers]]
for = "/build_test/Build/*.js"
  [headers.values]
  Content-Type = "application/javascript"

[[headers]]
for = "/build_test/Build/*.data.br"
  [headers.values]
  Content-Type     = "application/octet-stream"
  Content-Encoding = "br"

[[headers]]
for = "/build_test/Build/*.framework.js.br"
  [headers.values]
  Content-Type     = "application/javascript"
  Content-Encoding = "br"
